title: anti SF SF club
owner: The anti SF SF club
email:
description: A simple and minimalistic jekyll blogging theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
language: en
twitter_username:
github_username:

# Build settings
markdown: kramdown
theme: minima
highlighter:      rouge


permalink: /:year/:month/:day/:title/

compress_html:
  clippings: [div, p, ul, td, h1, h2]
  comments: all
  endings: all
  blanklines: false
  profile: false